"""empty message

Revision ID: 437b0c969352
Revises: 22628b5fe00d
Create Date: 2020-05-04 20:23:09.615254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437b0c969352'
down_revision = '22628b5fe00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('country')

    # ### end Alembic commands ###
