"""empty message

Revision ID: cec5bacf7695
Revises: 187c4430424a
Create Date: 2022-03-29 23:53:10.367466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec5bacf7695'
down_revision = '187c4430424a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customization_of_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bestseller', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('maps', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('market_share', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pricing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sales', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('search', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('topics', sa.Boolean(), nullable=True))
        batch_op.drop_column('monthlypricing')
        batch_op.drop_column('no_of_rating_map')
        batch_op.drop_column('weeklypricing')
        batch_op.drop_column('pricingcomparison')
        batch_op.drop_column('average_rating_map')
        batch_op.drop_column('retailpricing')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customization_of_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retailpricing', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('average_rating_map', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pricingcomparison', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('weeklypricing', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('no_of_rating_map', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('monthlypricing', sa.INTEGER(), nullable=True))
        batch_op.drop_column('topics')
        batch_op.drop_column('search')
        batch_op.drop_column('sales')
        batch_op.drop_column('pricing')
        batch_op.drop_column('market_share')
        batch_op.drop_column('maps')
        batch_op.drop_column('bestseller')

    # ### end Alembic commands ###
